name: ncf_seguros_indico
description: Aplicativo de indicações para NCF Seguros

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  # Gerenciamento de Estado
  provider: ^6.1.1
  # Injeção de Dependência
  get_it: ^7.6.4
  # Navegação
  go_router: ^13.0.0
  # Utilitários
  intl: ^0.19.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
