name: ncf_seguros_indico
description: Aplicativo de indicações para NCF Seguros

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.0
  # Gerenciamento de Estado
  provider: ^6.1.1
  # Injeção de Dependência
  get_it: ^8.0.3
  # Navegação
  go_router: ^15.1.2
  # Utilitários
  intl: ^0.20.2
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
