// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1u-FZdAWrRJtEL12sVXrSgoVqPNf3-tM',
    appId: '1:687603813143:web:db00202665d7de66ed0552',
    messagingSenderId: '687603813143',
    projectId: 'ncf-seguros-flutter',
    authDomain: 'ncf-seguros-flutter.firebaseapp.com',
    storageBucket: 'ncf-seguros-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1u-FZdAWrRJtEL12sVXrSgoVqPNf3-tM',
    appId: '1:687603813143:web:9c903bbf35e07d5bed0552',
    messagingSenderId: '687603813143',
    projectId: 'ncf-seguros-flutter',
    authDomain: 'ncf-seguros-flutter.firebaseapp.com',
    storageBucket: 'ncf-seguros-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC7xDdpWqtzcZoMHKPA2scpX8ega0Gloc',
    appId: '1:687603813143:android:bae7f922a5f9fed8ed0552',
    messagingSenderId: '687603813143',
    projectId: 'ncf-seguros-flutter',
    storageBucket: 'ncf-seguros-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xfn4w0JK9zzyyENKi_Gy8Y2N9VpYVbg',
    appId: '1:687603813143:ios:5717ab8ed4438e4bed0552',
    messagingSenderId: '687603813143',
    projectId: 'ncf-seguros-flutter',
    storageBucket: 'ncf-seguros-flutter.firebasestorage.app',
    iosBundleId: 'ncfseguros.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7xfn4w0JK9zzyyENKi_Gy8Y2N9VpYVbg',
    appId: '1:687603813143:ios:5717ab8ed4438e4bed0552',
    messagingSenderId: '687603813143',
    projectId: 'ncf-seguros-flutter',
    storageBucket: 'ncf-seguros-flutter.firebasestorage.app',
    iosBundleId: 'ncfseguros.app',
  );

}